services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:?Variável obrigatória ausente}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:?Variável obrigatória ausente}
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-PRUMO}
        NEXT_PUBLIC_WHATSAPP_TEMPLATE: ${NEXT_PUBLIC_WHATSAPP_TEMPLATE:-}
        NEXT_PUBLIC_TIME_ZONE: ${NEXT_PUBLIC_TIME_ZONE:-America/Sao_Paulo}
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:?Variável obrigatória ausente}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:?Variável obrigatória ausente}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:?Variável obrigatória ausente}
      LEADS_WEBHOOK_SECRET: ${LEADS_WEBHOOK_SECRET:?Variável obrigatória ausente}
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-PRUMO}
      NEXT_PUBLIC_WHATSAPP_TEMPLATE: ${NEXT_PUBLIC_WHATSAPP_TEMPLATE:-}
      NEXT_PUBLIC_TIME_ZONE: ${NEXT_PUBLIC_TIME_ZONE:-America/Sao_Paulo}
    ports:
      - "3000:3000"
    restart: unless-stopped
